os:
  - osx
osx_image: xcode10.3
language: swift
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TABTestKit.xcworkspace -scheme TABTestKit_ExampleUITests -sdk iphonesimulator12.4 -destination "OS=12.4,name=iPhone Xs" | xcpretty
- xcodebuild -workspace Example/TABTestKit.xcworkspace -scheme TABTestKit_ExampleUITests -sdk iphonesimulator12.4 -destination "OS=12.4,name=iPhone Xs" test -enableCodeCoverage YES
